name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
      - name: Lint and test
        run: yarn lint && yarn test

  deploy:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git for deployment
        run: |
          git config --global credential.helper store
          git config --global user.name "AppVeyor"
          git config --global user.email "ci@appveyor.com"
          echo "https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com" > $HOME/.git-credentials
      - name: Deploy
        run: npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"
